modLoader="javafml" #M
loaderVersion="[40,)" #M
license="GNU GPL v3, https://www.gnu.org/licenses/gpl-3.0.en.html" #M
issueTrackerURL="https://github.com/Hxrlio/Zorpalods/issues" #O

[[mods]] #M
modId="zorpalods" #M
version="${file.jarVersion}" #M
displayName="Zorpalods" #M
#updateJSONURL="NONE" #O
displayURL="https://modrinth.com/project/zorpalods" #O
logoFile="Zorpalods.png" #O
#credits="lxke on Discord for the concept and some mechanics." #O
authors="Hxrl" #O

# MATCH_VERSION = BOTH
# IGNORE_SERVER_VERSION = SERVER
# IGNORE_ALL_VERSION = CLIENT
# NONE = OTHER IExtensionPoint.DisplayTest for more
displayTest="MATCH_VERSION" # MATCH_VERSION is default (#O)

description='''
Adds Zorpalods, from Sluggeria, who are at war with Fortnite Island.
''' #M

[[dependencies.zorpalods]]
    modId="forge" #M
    mandatory=true #M
    versionRange="[40,)" #M
    # BEFORE / AFTER / NONE
    ordering="AFTER" #M
    # BOTH / CLIENT / SERVER
    side="BOTH" #M

[[dependencies.zorpalods]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.zorpalods]]
    modId="geckolib"
    mandatory=true
    versionRange="[3.0.57,)"
    ordering="AFTER"
    side="BOTH"